#pragma once
#include <Windows.h>
#include <iostream>
#include <thread>
#include <memory>
#include <vector>
#include <chrono>
#include "timers.h"
#include "event.h"
#include "input.h"
#include "display.h"
#include "vector2.h"
#include "level.h"
#include "CinnamonObject.h"
#include "Game.h"